{-# LANGUAGE BangPatterns #-}

module Main where

import Control.Exception (evaluate)
import Control.Monad (forM)
import Data.Bits ((.&.))
import Data.List (sort)
import System.CPUTime (getCPUTime)
import System.Environment (lookupEnv)
import Text.Printf (printf)
import Text.Read (readMaybe)

-- Self-contained decision kernels reduced from the pinned originals in ../originals.
-- They intentionally return small integer action codes instead of performing parser,
-- string-builder, or UTF-8 buffer effects.  That makes the branch shape measurable
-- without pretending this is a whole-library benchmark.

{-# NOINLINE ghcLexControl #-}
ghcLexControl :: Int -> Int
ghcLexControl code =
  case code of
    64 -> 0
    65 -> 1
    66 -> 2
    67 -> 3
    68 -> 4
    69 -> 5
    70 -> 6
    71 -> 7
    72 -> 8
    73 -> 9
    74 -> 10
    75 -> 11
    76 -> 12
    77 -> 13
    78 -> 14
    79 -> 15
    80 -> 16
    81 -> 17
    82 -> 18
    83 -> 19
    84 -> 20
    85 -> 21
    86 -> 22
    87 -> 23
    88 -> 24
    89 -> 25
    90 -> 26
    91 -> 27
    92 -> 28
    93 -> 29
    94 -> 30
    95 -> 31
    _ -> 32

{-# NOINLINE ghcShowLitCharClass #-}
ghcShowLitCharClass :: Int -> Int
ghcShowLitCharClass c | c > 127 = 0
ghcShowLitCharClass 127 = 1
ghcShowLitCharClass 92 = 2
ghcShowLitCharClass c | c >= 32 = 3
ghcShowLitCharClass 7 = 4
ghcShowLitCharClass 8 = 5
ghcShowLitCharClass 12 = 6
ghcShowLitCharClass 10 = 7
ghcShowLitCharClass 13 = 8
ghcShowLitCharClass 9 = 9
ghcShowLitCharClass 11 = 10
ghcShowLitCharClass 14 = 11
ghcShowLitCharClass _ = 12

{-# NOINLINE ghcUtf8LeadWidth #-}
ghcUtf8LeadWidth :: Int -> Int
ghcUtf8LeadWidth byte
  | byte <= 0x7f = 1
  | byte >= 0xc0 && byte <= 0xdf = 2
  | byte >= 0xe0 && byte <= 0xef = 3
  | byte >= 0xf0 && byte <= 0xf8 = 4
  | otherwise = 0

{-# NOINLINE aesonJsonValueClass #-}
aesonJsonValueClass :: Int -> Int
aesonJsonValueClass byte =
  case byte of
    34 -> 0
    123 -> 1
    91 -> 2
    102 -> 3
    116 -> 4
    110 -> 5
    45 -> 6
    _ | byte >= 48 && byte <= 57 -> 6
      | otherwise -> 7

-- Runtime-generated byte stream.  Masking to eight bits makes every benchmark
-- see the same domain while preventing the compiler from replacing the calls
-- with one constant result.
loop :: Int -> Int -> Int -> (Int -> Int) -> Int
loop 0 !_ !acc _ = acc
loop !n !x !acc f =
  let !x' = (x * 1103515245 + 12345) .&. 255
      !y = f x'
  in loop (n - 1) x' (acc + y) f

oneRun :: Int -> Int -> (Int -> Int) -> IO (Double, Int)
oneRun n seed f = do
  t0 <- getCPUTime
  checksum <- evaluate (loop n seed 0 f)
  t1 <- getCPUTime
  let elapsedPicoseconds = fromIntegral (t1 - t0) :: Double
      nsPerOp = elapsedPicoseconds / 1000.0 / fromIntegral n
  pure (nsPerOp, checksum)

bench :: Int -> String -> (Int -> Int) -> IO ()
bench n name f = do
  runs <- forM [1, 17, 33, 65, 129] $ \seed -> oneRun n seed f
  let times = sort (map fst runs)
      median = times !! 2
      checksum = sum (map snd runs)
  printf "%s\t%d\t%.3f\t%d\n" name n median checksum

iterations :: IO Int
iterations = do
  raw <- lookupEnv "BENCH_ITERS"
  pure $ case raw >>= readMaybe of
    Just n | n > 0 -> n
    _ -> 5000000

main :: IO ()
main = do
  n <- iterations
  putStrLn "benchmark\titerations\tmedian_cpu_ns_per_op\tchecksum"
  bench n "ghc_lex_control" ghcLexControl
  bench n "ghc_show_lit_char" ghcShowLitCharClass
  bench n "ghc_utf8_lead_width" ghcUtf8LeadWidth
  bench n "aeson_json_value" aesonJsonValueClass
